[pytest]
addopts = -v -s -rA --durations=10 --strict-markers --log-cli-level=INFO
    #-v  :shows each test/step status (passed, failed, skipped, etc.)
    #-s :shows stdout/stderr output from within tests (print statements)
    #-rA :shows test summary at the end of the test run (passed, failed, skipped, etc.)
    #--durations=10 :shows duration of 10 slowest tests, also shows total session time at the bottom.
    #--strict-markers :makes pytest error if you use a marker that isn't registered
    #--log-cli-level=INFO :shows log level INFO (to see INFO logs)
markers =
    critical: Critical tests that must pass
    extra: Extra tests (skipped by default, run with --run-extra or -m extra)
    xfail: Tests that are expected to fail
filterwarnings =
    # ignore Unknown host key warnings from paramiko
    ignore:Unknown.*host key:UserWarning:paramiko
# log cli format
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
# 'log_cli = true' + 'log_cli_level = INFO' → shows logs live during the test
log_cli = true
log_cli_level = INFO
# log_level CRITICAL suppresses the captured log replay at the end
log_level = CRITICAL
